"""basic_user

Revision ID: bc323c6b2981
Revises:
Create Date: 2017-02-10 11:21:44.792964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc323c6b2981'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    user_table = op.create_table(
        'user',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('email', sa.Unicode(length=256), nullable=False),
        sa.Column('user_type', sa.Unicode(length=16), nullable=False),
        sa.Column('password', sa.Unicode(length=128), nullable=False),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('email')
    )

    op.bulk_insert(
        user_table,
        [
            {
                'email': 'admin@localhost',
                # password: 'hunter2'
                'password': '2ba752e09466b4084f96fa6b17a3f90da4a3e62604818727a'
                            '14ee12941ced75a2eb988c46727df00',
                'user_type': 'admin'
            }
        ]
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
